image: jakzal/phpqa:1.38-alpine

cache:
  paths:
    - vendor/

stages:
  - lint
  - build
  - test

lint:
  stage: lint
  script:
    - phplint --no-cache

code-style:
  stage: lint
  script:
    - ecs check

validate-composer:
  stage: lint
  script:
    - composer validate

composer:
  stage: build
  before_script:
    - composer g require hirak/prestissimo
  script:
    - composer i --prefer-dist

phpstan:
  stage: test
  script:
    - phpstan analyze

psalm:
  stage: test
  script:
    - psalm

unit-tests:
  stage: test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  before_script:
    - php -v
  script:
    - php -dpcov.enabled=1 vendor/bin/phpunit --colors=never --coverage-text --whitelist=src
